apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytrip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flytrip
  template:
    metadata:
      labels:
        app: flytrip
    spec:
      containers:
        - name: flytrip
          image: 584612873567.dkr.ecr.us-east-1.amazonaws.com/flytrip-ci:latest
          ports:
            - containerPort: 8080
